-- 1. Admins Table
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    invite_token TEXT UNIQUE,
    account_setup INTEGER DEFAULT 0,
    is_super_admin INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Drivers Table
CREATE TABLE drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Riders Table
CREATE TABLE riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    address TEXT NOT NULL,
    password_hash TEXT,
    invite_token TEXT UNIQUE,
    token TEXT NOT NULL UNIQUE,
    account_setup INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Ride Requests Table
CREATE TABLE ride_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id BIGINT NOT NULL,
    week_date TEXT NOT NULL,
    destination TEXT DEFAULT 'CCB',
    ride_date TEXT,
    ride_time TEXT,
    notes TEXT,
    type TEXT DEFAULT 'auto',
    status TEXT DEFAULT 'pending',
    driver_id BIGINT,
    pickup_time TEXT,
    pickup_address TEXT,
    responded_at TIMESTAMPTZ,
    FOREIGN KEY (rider_id) REFERENCES riders(id) ON DELETE CASCADE,
    FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
    UNIQUE(rider_id, week_date, destination)
);

-- 5. Notification Config Table
CREATE TABLE notification_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled INTEGER DEFAULT 1,
    cron_schedule TEXT DEFAULT '0 17 * * 4',
    destination TEXT DEFAULT 'CCB',
    ride_day TEXT DEFAULT 'Sunday',
    message TEXT DEFAULT 'Do you want a ride to CCB this Sunday?',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the default notification configuration
INSERT INTO notification_config (updated_at) VALUES (NOW());

-- 6. Notification Log Table
CREATE TABLE notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_date TEXT NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    rider_count INTEGER
);